invisible-potions:
  - POTION
  - SPLASH_POTION
  - LINGERING_POTION

projectile-items:
  - BOW
  - CROSSBOW
  - TRIDENT
  - SNOWBALL
  - EGG
  - FISHING_ROD
  - ENDER_PEARL
  - EXPERIENCE_BOTTLE
  - SPLASH_POTION
  - LINGERING_POTION
  - FIREWORK_ROCKET

duration-logic: true

invisible-lore: "<#9B59B6>âœ¦ Invisible</#9B59B6>"
expiration-lore: "&7Expire: &f%date%"
date-format: "HH:mm dd/MM/yyyy"