invisible-potions:
  - POTION
  - SPLASH_POTION
  - LINGERING_POTION

projectile-items:
  - WOODEN_HOE
  - STONE_HOE
  - IRON_HOE
  - GOLDEN_HOE
  - DIAMOND_HOE
  - NETHERITE_HOE

# If true, players can see their own invisible items.
# If false, players see their own invisible items as air (invisible).
self-view-invisible-items: false

enchant-glint: true

invisible-lore: "<#9B59B6>âœ¦ Invisible</#9B59B6>"
